## https://www.freecodecamp.org/news/use-github-actions-to-automate-android-development/
#
#name: Android Publish
#
#on:
#  workflow_dispatch:
#
#jobs:
#  build:
#
#    runs-on: ubuntu-latest
#
#    steps:
#      - uses: actions/checkout@v3
#
#      - name: Set up JDK
#        uses: actions/setup-java@v3
#        with:
#          java-version: "11"
#
#      - name: Give run permission
#        run: chmod +x ./gradlew
#
#      - name: Run tests
#        run: ./gradlew test
#
#      - name: Build Project
#        run: ./gradlew build
#
#      - name: Build Release AAB
#        run: ./gradlew bundleRelease
#
#      - name: Sign AAB
#        uses: r0adkll/sign-android-release@v1
#        with:
#          releaseDirectory: app/build/outputs/bundle/release
#          signingKeyBase64: ${{ secrets.SIGN_KEY }}
#          alias: ${{ secrets.ALIAS }}
#          keyStorePassword: ${{ secrets.STORE_KEY_PASSWORD }}
#          keyPassword: ${{ secrets.KEY_PASSWORD }}
#
#      - name: Deploy to Play Store
#        uses: r0adkll/upload-google-play@v1
#        with:
#          serviceAccountJsonPlainText: ${{ secrets.SERVICE_ACCOUNT }}
#          packageName: johan.kovalsikoski.composeplayground
#          releaseFiles: app/build/outputs/bundle/release/app-release.aab
#          track: production